CC = g++
main: app.cpp Course.cpp Student.cpp Day.cpp Schedule.cpp Utils.cpp Roster.cpp
	$(CC) -o main.exe app.cpp Course.cpp Utils.h Student.cpp Day.cpp Schedule.cpp Utils.cpp Roster.cpp -I.

clean:
	rm -f *.exe